#[PLATFORM]-Add-BEGIN by Luoxingixng for gt9157 driver code.[2015.04.16]
obj-$(CONFIG_TOUCHSCREEN_GT9157) += goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT9157) += gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9157) += gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9157) += gt9xx_openshort.o
#[PLATFORM]-Add-End by Luoxingxing

