obj-$(CONFIG_GSL_TOUCHPANEL_DRIVER)   += gsl_ts_driver.o gsl_point_id.o gsl_ReadArrayData_c.o
$(obj)/gsl_point_id.o:$(srctree)/$(obj)/gsl_point_id
	cp $(srctree)/$(obj)/gsl_point_id $(obj)/gsl_point_id.o

